# Generated by Django 4.2.2 on 2024-03-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
